head -1 /Users/LeonardoAlmeida/Documents/projetos/busHadoop/data/topics.txt | parallel -j4 /Users/LeonardoAlmeida/Documents/projetos/busHadoop/config.py localhost:9092 {} 2 hdfs://localhost:9000/output
</Users/LeonardoAlmeida/Documents/projetos/busHadoop/data/topics.txt xargs -I % bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 2 --partitions 1 --topic %

spark-submit --jars lib/mongo-hadoop-spark-2.0.1.jar --driver-class-path lib/mongo-hadoop-spark-2.0.1.jar --py-files /usr/local/lib/python2.7/site-packages/pymongo_spark-0.1.dev0-py2.7.egg --packages org.mongodb.mongo-hadoop:mongo-hadoop-spark:2.0.2,org.xerial:sqlite-jdbc:3.15.1 --jars lib/spark-streaming-kafka-0-8-assembly_2.10-2.0.2.jar config.py hdfs://localhost:9000/output localhost 9093,9094 1002 2
spark-submit --packages org.mongodb.mongo-hadoop:mongo-hadoop-spark:2.0.1,org.xerial:sqlite-jdbc:3.15.1 --py-files /usr/local/lib/python2.7/site-packages/pymongo_spark-0.1.dev0-py2.7.egg config.py hdfs://localhost:9000/output localhost 9093,9094 1002 2
/Users/LeonardoAlmeida/Documents/Faculdade/UFSCar-Mestrado/Materias/BigData/spark/bin/spark-submit --driver-class-path lib/sqlite-jdbc-3.15.1.jar:lib/mongo-hadoop-spark-2.0.1.jar:lib/spark-streaming-kafka-0-10-assembly_2.10-2.0.1.jar --jars local:/Users/LeonardoAlmeida/Documents/projetos/busHadoop/lib/mongo-hadoop-spark-2.0.1.jar,local:/Users/LeonardoAlmeida/Documents/projetos/busHadoop/lib/spark-streaming-kafka-0-10-assembly_2.10-2.0.1.jar,local:/Users/LeonardoAlmeida/Documents/projetos/busHadoop/lib/sqlite-jdbc-3.15.1.jar --packages org.mongodb.mongo-hadoop:mongo-hadoop-spark:2.0.1,org.xerial:sqlite-jdbc:3.15.1,org.apache.spark:spark-streaming-kafka-0-8_2.10:2.0.1 --py-files pymongo_spark.py config.py hdfs://localhost:9000/output localhost 9093,9094 1002 2
/Users/LeonardoAlmeida/Documents/Faculdade/UFSCar-Mestrado/Materias/BigData/spark/bin/spark-submit --driver-class-path lib/sqlite-jdbc-3.15.1.jar:lib/mongo-hadoop-spark-2.0.1.jar --jars local:/Users/LeonardoAlmeida/Documents/projetos/busHadoop/lib/mongo-hadoop-spark-2.0.1.jar,local:/Users/LeonardoAlmeida/Documents/projetos/busHadoop/lib/spark-streaming-kafka-0-8-assembly_2.10-2.0.1.jar,local:/Users/LeonardoAlmeida/Documents/projetos/busHadoop/lib/sqlite-jdbc-3.15.1.jar --packages org.mongodb.mongo-hadoop:mongo-hadoop-spark:2.0.1,org.xerial:sqlite-jdbc:3.15.1,org.apache.spark:spark-streaming-kafka-0-10-assembly_2.10:2.0.1 --py-files pymongo_spark.py config.py hdfs://localhost:9000/output localhost 9093,9094 1002 2
/Users/LeonardoAlmeida/Documents/Faculdade/UFSCar-Mestrado/Materias/BigData/spark/bin/spark-submit --driver-class-path lib/sqlite-jdbc-3.15.1.jar:lib/mongo-hadoop-spark-2.0.1.jar --jars local:/lib/mongo-hadoop-spark-2.0.1.jar,local:/lib/spark-streaming-kafka-0-8-assembly_2.10-2.0.2.jar,local:/lib/sqlite-jdbc-3.15.1.jar --packages org.mongodb.mongo-hadoop:mongo-hadoop-spark:2.0.1 --py-files pymongo_spark.py config.py hdfs://localhost:9000/output localhost 9093,9094 1002 2


